services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: trail_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=DRIVER={ODBC Driver 17 for SQL Server};SERVER=DIST-6-505.uopnet.plymouth.ac.uk;DATABASE=COMP2001_MMcGovern;UID=MMcGovern;PWD=DlgB377*